CREATE TABLE IF NOT EXISTS UserPlayRecord (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  season VARCHAR(32) NOT NULL DEFAULT '2026',
  mode VARCHAR(32) NOT NULL DEFAULT 'Normal',
  matches INT UNSIGNED NOT NULL DEFAULT 0,
  wins INT UNSIGNED NOT NULL DEFAULT 0,
  losses INT UNSIGNED NOT NULL DEFAULT 0,
  draws INT UNSIGNED NOT NULL DEFAULT 0,
  kills INT UNSIGNED NOT NULL DEFAULT 0,
  deaths INT UNSIGNED NOT NULL DEFAULT 0,
  assists INT UNSIGNED NOT NULL DEFAULT 0,
  score INT UNSIGNED NOT NULL DEFAULT 0,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_user_play_record_user_season_mode (user_id, season, mode),
  INDEX idx_user_play_record_user_id (user_id, updated_at DESC),
  CONSTRAINT fk_user_play_record_user
    FOREIGN KEY (user_id)
    REFERENCES UserAccount (id)
    ON DELETE CASCADE
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;
